export const fonts = {
  families: {
    primaryBold: 'Inter-Bold',
    secondaryBold: 'Inter-Bold',
    primary: 'Inter-Regular',
    secondary: 'Inter-Regular',
    tertiary: 'Inter-Regular',
    extraBold: 'Inter-Black',
    semiBold: 'Inter-semiBold',
    medium: 'Inter-Medium',
  },
  fontSize: {
    xxs: 5,
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 17,
    '2xl': 20,
    '3xl': 21,
    '4xl': 24,
    '5xl': 27,
    '6xl': 32,
    '7xl': 64,
  },
};
